repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: requirements-txt-fixer
    language_version: python # Ensures 'python' is used

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus
    language_version: python

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
      - id: ruff-format
    language_version: python

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
    language_version: python

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.0"
    hooks:
      - id: pyproject-fmt
    language_version: python

  - repo: local
    hooks:
      - id: validate-filenames
        name: Validate filenames
        entry: python ./scripts/validate_filenames.py
        language: python
        pass_filenames: false
    language_version: python

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
    language_version: python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --explicit-package-bases
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
        additional_dependencies: [types-requests]
    language_version: python

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [toml, yaml]
    language_version: python
